[cxx-interop] Turn off caching for Clang Importer-related requests (#88727)
We seem to be hitting some spurious compilation errors that may be
caused by clang AST addresses being deallocated and reused between
module loading, making it unsound to cache based upon those addrs.
In particular, we sometimes see error messages saying things like:

error: reference type 'vector' must have 'retain:' Swift attribute

That doesn't make any sense since vector should never be a foreign
reference type, which suggests ForeignReferenceTypeInfoRequest may
be picking up a stale cached result requested on a different decl.

Disable caching for that request and others for now, so that these
requests are sound while we investigate Clang's pointer stability.

This is similar to 22dd716, which
also turns off caching for IsSafeUseOfCxxDecl for similar reasons.

Note that ClangTypeEscapability and CxxValueSemantics requests are
unchanged by this patch and are still cached, because they trigger
diagnostics that we don't to be duplicated as a result of removing
caching. In the future we should consider moving those diagnostics
out of these requests to make them idempotent (and safe to cache).

rdar://175540597